version: 2.1

jobs:
  
  create_aws_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: 
          name: Create CloudFormation services
          command: |
             aws cloudformation deploy \
                --template-file ./deploy_cloud_formation/cf_templates/resources.yml \
                --stack-name services-stack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1
      - run: |
          aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --output text

workflows:
  deploy-infrastructure-workflow:
    jobs:
      - create_aws_infrastructure
