version: 2.1

jobs:
  
  create_aws_infrastructure:
    working_directory: ~/project_<< pipeline.number >>
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout      
      - run: 
          name: Create CloudFormation services
          command: |
             aws cloudformation deploy \
                --template-file ./deploy_cloud_formation/cf_templates/resources.yml \
                --stack-name services-stack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1
      - run: | 
          echo "[ec2-instances]" > inventory && \
          aws ec2 describe-instances \
            --query 'Reservations[*].Instances[*].PublicIpAddress' \
            --output text >> inventory 
      - run: |
          yum install -y tar gzip && \
          mv inventory ./deploy_cloud_formation/ansible/inventory

      - attach_workspace:
          at: ~/project_<< pipeline.number >>

      - persist_to_workspace:
          root: ~/project_<< pipeline.number >>
          paths:
            - ./deploy_cloud_formation/ansible

  run-ansible_playbooks:
    working_directory: ~/project_<< pipeline.number >>
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["ea:43:42:b3:40:5f:88:9b:e5:a5:53:6a:9b:d6:2b:64"]
      - attach_workspace:
          at: ~/project_<< pipeline.number >>
      - run: 
          name: Install dependencies
          command: apk add --update ansible
      - run:
          name: Run ansible playbook
          command: |
            cd ./deploy_cloud_formation/ansible && \
            ls -l && ansible-playbook -i inventory main-remote.yml
      - run:
          name: Rollback cloudformation stack on fail
          command: |
              stackName=$(aws cloudformation describe-stacks --query Stacks[0].StackName) && \
              echo $(stackName) && \
              aws cloudformation delete-stack --stack-name $(stackName) && \
              echo "CloudFormation stack cleaning has being triggered. Please check!"
          when: on_fail

workflows:
  deploy-infrastructure-workflow:
    jobs:
      - create_aws_infrastructure
      - run-ansible_playbooks:
          requires:
            - create_aws_infrastructure
